name = "mediahub-5wd"
compatibility_date = "2024-01-01"

[build]
command = "npm run build && npm run build:pages"
cwd = "./mediahub"

pages_build_output_dir = ".vercel/output"

[[d1_databases]]
binding = "MOVIEDB"
database_name = "movieworld_db"
database_id = "ca2d92bc-8c59-48ec-9d72-1561e4627cdf"

[env.preview]
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_flags = ["nodejs_compat"]

[[env.production.d1_databases]]
binding = "MOVIEDB"
database_name = "moviedb"
database_id = "ca2d92bc-8c59-48ec-9d72-1561e4627cdf"

